from app.routes.database.aulas import *
from app.routes.database.usuarios_especiais import *
from app.routes.database.usuarios import *
from app.routes.database.pessoas import *
from app.routes.database.permissoes import *
from app.routes.database.laboratorios import *
from app.routes.database.reservas_fixas import *
from app.routes.database.aulas_ativas import *
from app.routes.database.historicos import *
from app.routes.database.semestres import *
from app.routes.database.reservas_temporarias import *