#flags de permissão
PERM_RESERVA_FIXA = 1
PERM_RESERVA_TEMPORARIA = 2
PERM_RESERVA_AUDITORIO = 4
PERM_ADMIN = 8
PERM_AUTORIZAR = 16
PERM_CMD_CONFIG = 32

#flags de formatação de data
DATA_NUMERICA = 0x1
DATA_ABREV = 0x2
DATA_COMPLETA = 0x4
HORA = 0x8
SEMANA_ABREV = 0x10
SEMANA_COMPLETA = 0x20

PERMISSIONS = {
    'FIXA': PERM_RESERVA_FIXA,
    'TEMP': PERM_RESERVA_TEMPORARIA,
    'AUDITORIO': PERM_RESERVA_AUDITORIO,
    'ADMIN': PERM_ADMIN,
    'AUTORIZAR': PERM_AUTORIZAR,
    'CONFIGURAR_COMANDOS': PERM_CMD_CONFIG
}

DATA_FLAGS = {
    'DATA_NUMERICA': DATA_NUMERICA,
    'DATA_ABREV': DATA_ABREV,
    'DATA_COMPLETA': DATA_COMPLETA,
    'HORA': HORA,
    'SEMANA_ABREV': SEMANA_ABREV,
    'SEMANA_COMPLETA': SEMANA_COMPLETA
}
