#flags de permissão
PERM_RESERVAS_FIXA = 1
PERM_RESERVAS_TEMPORARIA = 2
PERM_ADMIN = 4

#flags de formatação de data
DATA_NUMERICA = 0x1
DATA_ABREV = 0x2
DATA_COMPLETA = 0x4
HORA = 0x8
SEMANA_ABREV = 0x10
SEMANA_COMPLETA = 0x20

PERMISSIONS = {
    'FIXA': PERM_RESERVAS_FIXA,
    'TEMP': PERM_RESERVAS_TEMPORARIA,
    'ADMIN': PERM_ADMIN
}

DATA_FLAGS = {
    'DATA_NUMERICA': DATA_NUMERICA,
    'DATA_ABREV': DATA_ABREV,
    'DATA_COMPLETA': DATA_COMPLETA,
    'HORA': HORA,
    'SEMANA_ABREV': SEMANA_ABREV,
    'SEMANA_COMPLETA': SEMANA_COMPLETA
}
